version: "3.9"

services:
  mongo1:
    image: mongo:7
    container_name: mongo1
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo1_data:/data/db2
      - ./mongo-init:/docker-entrypoint-initdb.d
    command: ["--replSet", "rs0", "--bind_ip_all"]
    networks:
      - app-network

  mongo2:
    image: mongo:7
    container_name: mongo2
    restart: always
    volumes:
      - mongo2_data:/data/db2
    command: ["--replSet", "rs0", "--bind_ip_all"]
    networks:
      - app-network

  mongo3:
    image: mongo:7
    container_name: mongo3
    restart: always
    volumes:
      - mongo3_data:/data/db2
    command: ["--replSet", "rs0", "--bind_ip_all"]
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - CLIENT_URL=http://localhost:8000
      - COINGECKO_API_KEY=${COINGECKO_API_KEY:-}
      - MONGO_URI=mongodb://mongo1:27017,mongo2:27017,mongo3:27017/tradingAppDB?replicaSet=rs0
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-https://api.coingecko.com/api/v3}
        API_KEY: ${API_KEY:-}
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-https://api.coingecko.com/api/v3}
      - API_KEY=${API_KEY:-}
    container_name: frontend
    ports:
      - "8000:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:

networks:
  app-network:
    driver: bridge
