version: "3.9"

services:
  mongo_a:
    image: mongo:7
    container_name: mongo_a
    restart: always
    ports:
      - "27020:27017"
    volumes:
      - mongo_a_data:/data/db
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: ep_backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - COINGECKO_API_KEY=${COINGECKO_API_KEY:-}
      - MONGO_URI=mongodb://mongo_a:27017/tradingAppDB
    depends_on:
      - mongo_a
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-https://api.coingecko.com/api/v3}
        API_KEY: ${API_KEY:-}
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-https://api.coingecko.com/api/v3}
      - API_KEY=${API_KEY:-}
    container_name: ep_frontend
    ports:
      - "8000:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mongo_a_data:

networks:
  app-network:
    driver: bridge
